Update Cleanup-old-image.yml

diff --git a/.github/workflows/Cleanup-old-image.yml b/.github/workflows/Cleanup-old-image.yml
--- a/.github/workflows/Cleanup-old-image.yml
+++ b/.github/workflows/Cleanup-old-image.yml
@@ -13,10 +13,14 @@ jobs:
     steps:
       # Step 1: Log in to Docker Hub
       - name: Log in to Docker Hub
-        uses: docker/login-action@v2
-        with:
-          username: ${{ secrets.DOCKER_USERNAME }}
-          password: ${{ secrets.DOCKER_PASSWORD }}
+        run: |
+          RESPONSE=$(curl -s -u ${{ secrets.DOCKER_USERNAME }}:${{ secrets.DOCKER_PASSWORD }} "https://hub.docker.com/v2/users/login/")
+          TOKEN=$(echo "$RESPONSE" | jq -r '.token')
+          if [ "$TOKEN" == "null" ] || [ -z "$TOKEN" ]; then
+            echo "Error: Unable to retrieve Docker Hub token. Response: $RESPONSE"
+            exit 1
+          fi
+          echo "TOKEN=$TOKEN" >> $GITHUB_ENV
 
       # Step 2: List all image tags
       - name: List All Image Tags
